baseURL = "https://lego.tole.es"
languageCode = "es-es"
title = "Los Ãºltimos descuentos detectados!"
theme = "hugo-shopping-product-catalogue-simple"

[Params]
description = "Lego barato! "
channel = "https://t.me/s/brickchollo"
ga = "G-CCLRP3R12J"
yandex = "27d3b6cce1d74b40"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]